version: '3'
services:
  app:
    mem_limit: 1g
    cpus: 1
    build:
      context: ./
      target: dev
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
    ports:
      - "80:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:tLmYfUrrZITzLIkSjFnV+PCAFxkdU+duUxjVSIlrrHo=
      - DB_CONNECTION=mysql
    networks:
      - laravel
  mysql:
    image: 'mysql:8.0'
    mem_limit: 1g
    cpus: 0.5
    container_name: myapp-mysql
    working_dir: /var/www/myapp
    volumes:
       - 'mysql8:/var/lib/mysql'
       - './db/init.sql:/docker-entrypoint-initdb.d/01init.sql'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
    laravel:
        driver: bridge
volumes:
    mysql8:
    app:
    nginx:
