version: '3'
services:
  app:  
    mem_limit: 4g
    cpus: 1
    build:
      context: ./
      target: dev
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
    ports:
      - "8082:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:tLmYfUrrZITzLIkSjFnV+PCAFxkdU+duUxjVSIlrrHo=
      - DB_CONNECTION=mysql 
    networks:
      - laravel
    depends_on:
      - mysql    
  mysql:
    image: 'mysql:8.0'
    mem_limit: 1g
    cpus: 0.5
    container_name: myapp-mysql
    working_dir: /var/www/myapp
    volumes:
       - 'mysql8:/var/lib/mysql'
       - './db/init.sql:/docker-entrypoint-initdb.d/01init.sql'
    ports:
      - "3306:3306"
    environment:   
      - MYSQL_ROOT_PASSWORD=root   
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root 
    networks:
      - laravel  
networks:
    laravel:
        driver: bridge
volumes:
    mysql8:
        driver: local